version: '3'
services:
  users:
    build: .
    ports:
     - "8000:8000"
    depends_on:
     - mongo
  mongo:
    image: "mongo:3.6.6"
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo-data: